# -*- coding: utf-8 -*-
"""
RoadTo — treść stron „Trasy” (8 tras na Kilimandżaro).

Każda trasa = mapa (przełącznik w build_trasy) + główka (meta) + lista
„Sprawdzi się, jeśli” + dni (szare karty: Dystans/Przewyższenie/Czas/Strefa/
Temperatura + opis) + tabela różnic wersji.

Odtworzone 1:1 ze screenów z Framera. Edytujesz tu, potem `python3 build_site.py`.
Klucz `key` musi odpowiadać nazwie trasy w build_trasy (ROUTES_MAPS).

Struktura dnia:  dict(title=..., stats=[("Dystans","..."), ...], desc="...", note="...")
Tabela:          dict(cols=[...], rows=[[...], ...])  lub None
"""

# Standardowe wiersze tabeli „różnic wersji” powtarzające się na trasach 7/8-dniowych
TABLE_78 = dict(
    cols=["Wersja", "Aklimatyzacja", "Czas na regenerację", "Skuteczność wejścia"],
    rows=[
        ["7 dni", "mniejsza – brak noclegu w Shira 1", "mniej odpoczynku, intensywniejsze wejście", "umiarkowana (~80–85%)"],
        ["8 dni", "lepsza – stopniowy wzrost wysokości (Shira 1 + Shira 2)", "więcej czasu na adaptację i sen", "bardzo wysoka (~90–95%)"],
    ],
    title="Różnice między wersją 7- a 8-dniową:",
)

ROUTES = {

    # ------------------------------------------------------------------ #
    "Marangu": dict(
        title='Marangu („Coca-Cola Route”)',
        meta="Długość 72 km  |  Czas 5–6 dni  |  Trudność umiarkowana  |  Przewyższenie: 4035 m",
        good_if_title="Sprawdzi się, jeśli:",
        good_if=[
            "masz umiarkowaną kondycję, ale dużą determinację",
            "wolisz łagodniejsze podejścia",
            "wolisz spać w schroniskach zamiast w namiotach",
            "szukasz najbardziej budżetowej opcji wejścia na szczyt",
            "cenisz sobie towarzystwo innych trekkerów i bardziej społeczną atmosferę",
            "Szukasz „bezpiecznej” ewakuacji w razie problemów (szlak wejścia = szlak zejścia).",
        ],
        days=[
            dict(title="Dzień 1: Marangu Gate 1860m → Mandara Hut 2700m",
                 stats=[("Dystans", "ok. 8 km"), ("Przewyższenie", "+840 m"), ("Czas przejścia", "4–5 godzin"),
                        ("Temperatura", "15–20°C w ciągu dnia, 5–10°C w nocy"), ("Strefa klimatyczna", "las deszczowy")],
                 desc="Wędrówka zaczyna się w wilgotnym, pachnącym lesie tropikalnym. Ścieżka prowadzi przez gęstwinę pełną paproci, mchów i drzew figowych. W koronach pohukują turaki i dzioborożce, a po gałęziach przemykają nieśmiało błękitne małpy colobus. Wilgoć osiada na ubraniach, a powietrze jest ciężkie i pełne dźwięków."),
            dict(title="Dzień 2: Mandara Hut 2700 m → Horombo Hut 3720m",
                 stats=[("Dystans", "ok. 12 km"), ("Przewyższenie", "+1 020 m"), ("Czas przejścia", "5–6 godzin"),
                        ("Temperatura", "10–15°C w dzień, 0–5°C w nocy"), ("Strefa klimatyczna", "wrzosowiska i zarośla górskie")],
                 desc="Las ustępuje miejsca otwartej przestrzeni. Pojawiają się olbrzymie senecje, lobelie i widoki na Mawenzi – postrzępiony, wulkaniczny szczyt. Powietrze staje się chłodniejsze i suchsze. Na tym etapie wielu trekkerów zaczyna odczuwać pierwsze objawy wysokości: zmęczenie, senność, lekki ból głowy."),
            dict(title="Dzień 3: Horombo Hut – dzień aklimatyzacyjny (tylko w wersji 6-dniowej)",
                 stats=[("Dystans", "~4–8 km (zależnie od trasy)"), ("Przewyższenie", "+260–580 m (w górę), następnie powrót w dół"),
                        ("Czas przejścia", "3–4 godziny"), ("Temperatura", "10–15°C w dzień, 0–5°C w nocy"),
                        ("Cel", "lepsza adaptacja do wysokości")],
                 desc="To kluczowy dzień – organizm dostaje czas, by się zaadaptować. Trekking do Zebra Rocks lub w stronę Mawenzi pozwala na klasyczne „walk high, sleep low”. Krajobraz jest surowy, wietrzny, ale rozległy – widoki zapierają dech. Wieczorem wracasz do Horombo i czujesz, że ciało zaczyna się dostosowywać."),
            dict(title="Dzień 4: Horombo Hut 3720m → Kibo Hut 4703m",
                 stats=[("Dystans", "ok. 10 km"), ("Przewyższenie", "+983 m"), ("Czas przejścia", "6–8 godzin"),
                        ("Temperatura", "5–10°C w dzień, -5°C w nocy"), ("Strefa klimatyczna", "strefa alpejska i skalista pustynia")],
                 desc="To długa, powolna wędrówka przez kamienistą, pozbawioną życia pustynię. Kibo majaczy na horyzoncie jak nieosiągalna twierdza. Każdy krok w rozrzedzonym powietrzu wymaga skupienia. Noc w Kibo jest chłodna, surowa – to ostatnia szansa na odpoczynek przed szczytem."),
            dict(title="Dzień 5: Kibo Hut 4703m → Uhuru Peak 5895m → Horombo Hut 3720m",
                 stats=[("Dystans", "~21 km (6 km do szczytu, 15 km zejścia)"), ("Przewyższenie w górę", "+1 192 m"),
                        ("Przewyższenie w dół", "-2 175 m"), ("Czas przejścia", "12–14 godzin (łącznie)"),
                        ("Temperatura", "-10°C do -15°C w nocy, 0–5°C po wschodzie słońca"), ("Strefa klimatyczna", "lodowiec, śnieg, skała")],
                 desc="Startujesz o północy. Wspinaczka w ciemności prowadzi przez Hans Meyer Cave i Gillman's Point (5 685 m), gdzie wielu ma kryzys. Oddech płytki, krok za krokiem. O wschodzie słońce rozświetla lodowce i śnieg, a Ty stajesz na Uhuru Peak – najwyższym punkcie Afryki. Emocje buzują. Zejście długie, ale umysł już gdzie indziej."),
            dict(title="Dzień 6: Horombo Hut 3720m → Marangu Gate 1860m",
                 stats=[("Dystans", "ok. 20 km"), ("Przewyższenie", "-1 860 m"), ("Czas przejścia", "6–7 godzin"),
                        ("Temperatura", "15–20°C w ciągu dnia, 5–10°C w nocy"), ("Strefy klimatyczne", "od wrzosowisk po tropikalny las")],
                 desc="Zejście to ostatni wysiłek – kolana dają o sobie znać. Z każdym krokiem wracasz do świata dźwięków i zieleni. Na dole czeka certyfikat, zimne piwo i wielka satysfakcja."),
        ],
        table=dict(
            cols=["Wersja", "Aklimatyzacja", "Czas na regenerację", "Skuteczność wejścia"],
            rows=[
                ["5 dni", "mniejsza, bez dnia aklimatyzacyjnego", "szybciej, intensywniej", "niższa (~70–75%)"],
                ["6 dni", "lepsza – z dodatkowym dniem na Horombo", "większa szansa na sukces", "wyższa (~85–92%)"],
            ],
            title="Różnice między wersją 5- a 6-dniową:",
        ),
    ),

    # ------------------------------------------------------------------ #
    "Machame": dict(
        title="Machame Route",
        meta="Długość: ok. 62 km  |  Czas: 6–7 dni  |  Trudność: umiarkowanie wysoka fizycznie i aklimatyzacyjnie  |  Przewyższenie: ok. 4045 m",
        good_if_title="Sprawdzi się, jeśli:",
        good_if=[
            "chcesz wejść popularną i malowniczą trasą z dobrą aklimatyzacją",
            "lubisz urozmaicone tereny: od lasów deszczowych po księżycowe pustynie",
            "chcesz nocować w namiocie, z dala od utwardzonych dróg",
            "szukasz trasy z klasycznym podejściem „walk high, sleep low”",
            "masz przyzwoitą kondycję i chcesz mieć czas na regenerację i zdjęcia",
            "chcesz poczuć atmosferę wyprawy – z obozami, kolacją w messie i poranną kawą z widokiem na Kibo",
        ],
        days=[
            dict(title="Dzień 1: Machame Gate 1800m → Machame Camp 2835m",
                 stats=[("Dystans", "~11 km"), ("Przewyższenie", "+1 035 m"), ("Czas", "5–7 godzin"),
                        ("Temperatura", "18–22°C w dzień, 8–10°C w nocy"), ("Strefa", "las deszczowy")],
                 desc="Wędrówka zaczyna się niepozornie – miękki, leśny grunt pod stopami, wilgotne powietrze, dźwięki cykad i ptaków. Tropikalny las wciąga Cię gęstością zieleni, mchem oblepiającym gałęzie i parującą ziemią. To dzień, który pozwala złapać rytm – spokojny marsz, głęboki oddech, pierwsze krople potu na karku. Choć wysokościowo to dopiero początek, ciało czuje zmianę. Obóz wśród drzew – cichy, wilgotny, jak zanurzony w mglistym śnie. To tylko przedsionek wyprawy – góra dopiero się zaczyna."),
            dict(title="Dzień 2: Machame Camp 2835m → Shira Camp 3750m",
                 stats=[("Dystans", "~5 km"), ("Przewyższenie", "+915 m"), ("Czas", "4–6 godzin"),
                        ("Temperatura", "10–15°C w dzień, 0–5°C w nocy"), ("Strefa", "wrzosowiska / zarośla wysokogórskie")],
                 desc="Zostawiasz za sobą las – wkraczasz na otwarte zbocza płaskowyżu Shira. Szlak zaczyna piąć się coraz stromiej, teren otwiera się na przestrzeń i horyzont. Złociste trawy, skarlałe krzewy i ciemne głazy wyznaczają kierunek marszu. Powietrze robi się rzadsze, słońce bardziej intensywne. Nocleg na Shira to pierwsze prawdziwe zetknięcie z górską surowością – zimny wiatr, rozległa pustka i poczucie, że jesteś już wysoko."),
            dict(title="Dzień 3: Shira Camp 3750m → Lava Tower 4600m → Barranco Camp (3900 m)",
                 stats=[("Dystans", "~10 km"), ("Przewyższenie", "+850 m / -700 m"), ("Czas", "6–8 godzin"),
                        ("Strefa", "alpejska pustynia"), ("Temperatura", "5–10°C w dzień, -2°C do -5°C w nocy")],
                 desc="To dzień „walk high, sleep low” – klasyczny dla aklimatyzacji. Podejście pod Lava Tower daje Ci lekcję pokory: wysokość, suchość, osłabienie, czasem ból głowy. Ale to także dzień niesamowitych pejzaży – czarne skały, księżycowe zbocza, czerwone piargi. Lava Tower przypomina strażnika góry – monumentalna, poszarpana, obojętna. Potem zejście do Barranco – łagodniejsze, ale wciąż wymagające. Obóz u stóp słynnej Barranco Wall to jeden z najpiękniejszych na trasie – z widokiem na senecje i wulkan Mawenzi w tle."),
            dict(title="Dzień 4: Barranco Camp (3900 m) → Karanga Camp (3995 m)",
                 stats=[("Dystans", "~5 km"), ("Przewyższenie", "+95 m (ale z dużymi podejściami i zejściami)"), ("Czas", "4–5 godzin"),
                        ("Strefa", "skaliste przełęcze i alpejskie doliny"), ("Temperatura", "5–10°C w dzień, -3°C w nocy")],
                 desc="Barranco Wall – nazywana „Śniadaniową Ścianą” – wygląda groźnie, ale daje dużo frajdy. Trzeba używać rąk, balansować na głazach, momentami czuć ekspozycję. Potem falujący teren, doliny, podejścia, zejścia – dzień niepozorny, ale męczący. Karanga to przystanek strategiczny: odpoczynek, aklimatyzacja, ciepła zupa i przygotowanie psychiczne do dalszej drogi.",
                 note="W opcji 6 dniowej zdobywania szczytu w tym dniu idzie się od razu do obozu Barafu pomijając nocleg w Karanga."),
            dict(title="Dzień 5: Karanga Camp (3995 m) → Barafu Camp (4673 m)",
                 stats=[("Dystans", "~4 km"), ("Przewyższenie", "+678 m"), ("Czas", "3–4 godziny"),
                        ("Strefa", "pustynia wysokogórska"), ("Temperatura", "0–5°C w dzień, -10°C w nocy")],
                 desc="Szlak prowadzi przez pustynię alpejską – jałową, kamienistą, z pozostałościami dawnych wylewów lawy. Barafu to miejsce surowe: wietrzne, zimne, odsłonięte. Obóz przypomina księżycową bazę – rozrzucone namioty, cisza, oczekiwanie. Nikt tu nie rozmawia długo – to czas odpoczynku przed szczytem. Posiłek, przygotowanie sprzętu, trochę snu. I czekanie na noc. Czas wejść w najważniejszy fragment drogi."),
            dict(title="Dzień 6: Barafu Camp 4673 m → Uhuru Peak 5895 m → Mweka Camp 3100 m",
                 stats=[("Dystans", "~17 km (5 km podejścia, 12 km zejścia)"), ("Przewyższenie", "+1 222 m / -2 795 m"),
                        ("Czas", "12–14 godzin"), ("Strefa", "lodowiec → wrzosowiska"),
                        ("Temperatura", "-10°C do -15°C w nocy, 0–5°C po świcie, 10–15°C w Mweka Camp")],
                 desc="Start w środku nocy – w świetle czołówek, w ciszy, w chłodzie. Marsz jest wolny, każdy krok to wysiłek. Po świcie – Stella Point i emocje. Potem Uhuru Peak – najwyższy punkt Afryki. Zdjęcie, łzy, duma. Zejście to fizyczna walka: drżące nogi, osuwające się kamienie. Ale z każdym metrem w dół wraca ciepło i tlen. W Mweka Camp – odpoczynek, sen jak nagroda."),
        ],
        table=dict(
            cols=["Wersja", "Aklimatyzacja", "Czas na regenerację", "Skuteczność wejścia"],
            rows=[
                ["7 dni", "mniejsza – brak noclegu w Shira 1", "mniej odpoczynku, intensywniejsze wejście", "umiarkowana (~80–85%)"],
                ["8 dni", "lepsza – stopniowy wzrost wysokości (Shira 1 + Shira 2)", "więcej czasu na adaptację i sen", "bardzo wysoka (~90–95%)"],
            ],
            title="Różnice między wersją 7- a 8-dniową:",
        ),
    ),

    # ------------------------------------------------------------------ #
    "Lemosho": dict(
        title="Lemosho",
        meta="Długość 70–72 km  |  Czas 7–8 dni  |  Trudność umiarkowana do wymagającej  |  Przewyższenie: 3795 m",
        good_if_title="Idealna opcja dla Ciebie, jeśli:",
        good_if=[
            "Szukasz najpiękniejszych widoków na Kilimandżaro",
            "Chcesz uniknąć tłumów pierwszych dni na trasie",
            "Masz ochotę na pełniejsze górskie doświadczenie – z namiotami, ciszą i przygodą",
            "Zależy Ci na lepszej aklimatyzacji i większych szansach na szczyt",
            "Lubisz różnorodność – Lemosho oferuje las, sawannę, pustynię i lodowiec",
            "Jesteś w dobrej formie i chcesz poczuć, że naprawdę zdobywasz górę",
            "Masz więcej czasu – minimum 7–8 dni, by przejść ją komfortowo",
        ],
        days=[
            dict(title="Dzień 1: Lemosho Gate 2100 m → Mti Mkubwa Camp 2650 m",
                 stats=[("Dystans", "~7 km"), ("Przewyższenie", "+550 m"), ("Czas przejścia", "3–4 godziny"),
                        ("Strefa klimatyczna", "las deszczowy"), ("Temperatura", "15–20°C w dzień, 8–10°C w nocy")],
                 desc="Wchodzisz w soczystą zieleń lasu deszczowego – tropikalna gęstwina otacza Cię z każdej strony. Powietrze jest ciepłe i wilgotne, pachnie ziemią, liśćmi i życiem. Ścieżka prowadzi przez chaszcze, korzenie i porośnięte mchem skały. Co chwilę słychać dzioborożce, czasem błyska wśród gałęzi ogon nieśmiałej małpy colobus. Ten dzień nie przypomina jeszcze wysokogórskiego trekkingu – to zanurzenie w dzikiej Tanzanii, pierwsze kroki w stronę czegoś znacznie większego. Mti Mkubwa, czyli „Wielkie Drzewo”, to mały leśny obóz – noc spokojna, ciepła, z szumem liści w tle."),
            dict(title="Dzień 2: Mti Mkubwa 2650m → Shira 1 Camp 3610 m",
                 stats=[("Dystans", "~8 km"), ("Przewyższenie", "+960 m"), ("Czas przejścia", "5–6 godzin"),
                        ("Strefa klimatyczna", "wrzosowiska i zarośla"), ("Temperatura", "10–15°C w dzień, 0–5°C w nocy")],
                 desc="Rano żegnasz las, a niemal od razu pojawiają się pierwsze otwarte widoki. Wspinaczka prowadzi przez porośnięte krzewami stoki, skąd rozpościerają się panoramy zachodniej części Kilimandżaro. Teren staje się bardziej kamienisty, a roślinność rzadsza – dominują lobelie i senecje, rosnące jak bajkowe totemy. Kibo – główny wierzchołek – pojawia się pierwszy raz na horyzoncie, pokryty lodem i wydający się wciąż bardzo odległy. Szlak przechodzi przez kilka tarasów wulkanicznych, a im bliżej Shira 1, tym silniejszy może być wiatr. Obóz leży na otwartej przestrzeni płaskowyżu – rozciągnięty, z niskimi roślinami, wspaniałymi zachodami słońca i zimnymi nocami. Czuć, że to już wysokie góry.",
                 note="Wersja 7-dniowa pomija ten dzień z noclegiem w Shira 1 Camp – w tym dniu idzie się dłużej aż do Shira 2."),
            dict(title="Dzień 3: Shira 1 Camp 3610 m → Shira 2 Camp 3850 m",
                 stats=[("Dystans", "~7 km"), ("Przewyższenie", "+240 m"), ("Czas przejścia", "3–4 godziny"),
                        ("Strefa klimatyczna", "pustynia wysokogórska"), ("Temperatura", "8–12°C w dzień, 0–4°C w nocy")],
                 desc="Ten dzień wydaje się łatwy – ni_duże przewyższenie, krótki dystans – ale to pozory. Na tej wysokości marsz staje się wolniejszy, a każdy krok przypomina, że jesteś już ponad 3 500 m n.p.m. Szlak prowadzi przez księżycowy krajobraz Shira Plateau – wielką równinę zastygłej lawy z widokiem na lodowe czapy Kibo. Wędrujesz przez teren niemal pozbawiony roślinności, z czarną ziemią i białymi chmurami tańczącymi pod niebem. Obóz Shira 2 jest odsłonięty i często nawiedzany przez wiatr – temperatura wieczorem może gwałtownie spaść. To dobry moment na pierwsze refleksje i spokojne wsłuchanie się w rytm gór."),
            dict(title="Dzień 4: Shira 2 3850 m → Lava Tower 4600 m → Barranco Camp (3900 m)",
                 stats=[("Dystans", "~10 km"), ("Przewyższenie", "+750 m / -700 m"), ("Czas przejścia", "6–7 godzin"),
                        ("Strefa klimatyczna", "alpejska pustynia / strefa subarktyczna"), ("Temperatura", "5–10°C w dzień, -2°C w nocy")],
                 desc="To jeden z najważniejszych dni aklimatyzacyjnych na całej trasie. Podejście pod Lava Tower, skalną iglicę wznoszącą się na 4 600 m n.p.m., to solidne wyzwanie – dla nóg, płuc i głowy. Powietrze staje się wyraźnie rzadsze, a każdy krok wymaga większego wysiłku. Objawy wysokościowe mogą się nasilić: zawroty głowy, zadyszka, osłabienie – dlatego tempo jest wolne, a postój przy Lava Tower strategiczny. Następnie schodzisz kilkaset metrów w dół do Barranco – przepięknego obozu położonego w dolinie, otoczonego olbrzymimi senecjami i stromymi ścianami. To „walk high, sleep low” w praktyce – kluczowe dla Twojej adaptacji. Zachód słońca nad Kibo z tej perspektywy zapiera dech w piersiach."),
            dict(title="Dzień 5: Barranco Camp 3900m → Karanga Camp 3995 m",
                 stats=[("Dystans", "~6 km"), ("Przewyższenie", "+95 m (ale duże podejście na początku)"), ("Czas przejścia", "4–5 godzin"),
                        ("Strefa", "skaliste ściany i doliny"), ("Temperatura", "5–10°C w dzień, -3°C w nocy")],
                 desc="Dzień zaczyna się mocno – niemal od razu atakujesz Barranco Wall, stromą ścianę o wysokości około 300 metrów. Choć wygląda groźnie, wspinaczka jest bardziej emocjonująca niż techniczna – to moment, który wiele osób zapamiętuje jako punkt przełomowy. Z góry rozciągają się zapierające dech widoki na doliny i lodowce. Potem szlak faluje: w górę, w dół, przez skaliste przełęcze i doliny z wyschniętymi strumieniami. Karanga Camp pojawia się nagle – niewielka przestrzeń na grani, często wystawiona na wiatr. Dzień krótki, ale potrzebny – to ważny etap regeneracyjny przed ostatnim podejściem pod obóz szczytowy."),
            dict(title="Dzień 6: Karanga Camp 3995 m → Barafu Camp 4673 m",
                 stats=[("Dystans", "~4 km"), ("Przewyższenie", "+678 m"), ("Czas przejścia", "3–4 godziny"),
                        ("Strefa", "pustynia wysokogórska"), ("Temperatura", "0–5°C w dzień, -5 do -10°C w nocy")],
                 desc="Krótki, ale wymagający etap przez surowe, skaliste pustkowie. Szlak prowadzi przez rumowiska wulkaniczne i sypkie piargi – przy każdym kroku ziemia może się osuwać pod stopami. Otoczenie jest niemal całkowicie pozbawione życia – to strefa pustyni alpejskiej, gdzie przetrwają tylko najbardziej odporne organizmy. Obóz Barafu leży na wysoko położonym grzbiecie, często pod śniegiem, z panoramicznym widokiem na wschód. Tu już nikt nie myśli o zdjęciach – wieczór służy pakowaniu plecaka, przygotowywaniu warstw odzieży i mentalnemu nastawieniu na nocny atak szczytowy. Sen, jeśli w ogóle przychodzi, jest lekki i niespokojny."),
            dict(title="Dzień 7: Barafu 4673 m → Uhuru Peak 5 895 m → Mweka Camp 3100 m",
                 stats=[("Dystans", "5 km podejścia, 12 km zejścia"), ("Przewyższenie", "+1 222 m / -2 795 m"),
                        ("Czas przejścia", "12–14 godzin"), ("Temperatura", "-10°C do -15°C w nocy, 0–5°C po wschodzie"),
                        ("Strefa", "lodowiec, strefa subarktyczna → wrzosowiska")],
                 desc="Atak szczytowy rozpoczyna się tuż po północy. Wyruszasz w całkowitej ciemności, w ciszy przerywanej tylko oddechami i skrzypieniem butów po żwirze. Każdy krok na stromym zboczu wymaga skupienia i silnej woli. Im bliżej grani, tym zimniej – temperatura może spaść poniżej -15°C. Stella Point wita Cię o świcie – a od niego jeszcze godzina marszu do Uhuru Peak, najwyższego punktu Afryki. Gdy stoisz na szczycie, wszystko cichnie – tylko lodowce, przestrzeń i wzruszenie. Zejście z powrotem do Barafu to pierwszy etap ulgi, ale prawdziwe zmęczenie przychodzi dopiero później – zejście aż do Mweka Camp to kilkaset metrów w pionie po sypkim gruncie. To najdłuższy, najbardziej wyczerpujący dzień wyprawy – ale też najpiękniejszy."),
        ],
        table=TABLE_78,
    ),

    # ------------------------------------------------------------------ #
    "Rongai": dict(
        title="Rongai",
        meta="Długość 73–75 km  |  Czas 6–7 dni  |  Trudność umiarkowana fizycznie, łatwiejsza technicznie  |  Przewyższenie: 3531 m",
        good_if_title="Dobrze się sprawdzi, jeśli planujesz:",
        good_if=[
            "Szukasz najspokojniejszej i najmniej uczęszczanej trasy na szczyt",
            "Chcesz zacząć od strony kenijskiej, z suchszym klimatem i otwartymi widokami",
            "Wolisz łagodne podejścia i mniej stromych odcinków",
            "Nie boisz się namiotów, ale cenisz suchą pogodę (idealna w porze deszczowej)",
            "Zależy Ci na większej szansie na suchą i samotność na szlaku",
            "Masz umiarkowaną kondycję i szukasz trasy, która rośnie stopniowo w trudność",
            "Chcesz połączyć trekking z obserwacją dzikiej przyrody i krajobrazów sawanny",
        ],
        days=[
            dict(title="Dzień 1: Rongai Gate 2364 m → Simba Camp 2 671 m",
                 stats=[("Dystans", "~8 km"), ("Przewyższenie", "+307 m"), ("Czas przejścia", "3–4 godziny"),
                        ("Temperatura", "18–22°C w dzień, 8–12°C w nocy"), ("Strefa klimatyczna", "suche wrzosowiska, las alpejski")],
                 desc="Wyprawa rozpoczyna się od kenijskiej strony góry – tu, gdzie klimat jest bardziej suchy, a krajobraz przypomina sawannę. Zamiast wilgotnego lasu tropikalnego, wędrujesz przez złociste trawy, krzewy i rozrzucone drzewa akacjowe. Szlak pnie się łagodnie, a wokół jest cisza – tylko śpiew ptaków, szelest trawy i ślady dzikich zwierząt. Spotkasz pasterzy i usłyszysz może nawoływania guźców. W oddali po raz pierwszy rysuje się wulkaniczna sylwetka Mawenzi – tajemnicza i surowa. Obóz Simba to niewielkie, spokojne miejsce wśród wrzosowisk – idealne, by wejść w rytm wyprawy. Noc jest chłodna, cicha i pełna nieba."),
            dict(title="Dzień 2: Simba Camp 2671 m → Second Cave Camp 3 450 m",
                 stats=[("Dystans", "~9 km"), ("Przewyższenie", "+ m"), ("Czas przejścia", "5–6 godzin"),
                        ("Temperatura", "12–18°C w dzień, 5–8°C w nocy"), ("Strefa", "wrzosowiska i zarośla wysokogórskie")],
                 desc="Z każdym krokiem zostawiasz za sobą sawannowy klimat i zbliżasz się do wysokogórskiej przestrzeni. Teren otwiera się szeroko – po jednej stronie grzbiet Mawenzi, po drugiej doliny i urwiska prowadzące w stronę równin. Szlak jest suchy, a powietrze przyjemnie chłodne. Wędrówka jest spokojna, bez stromych podejść – to dobry moment na wdrożenie zasady „pole pole”. W Second Cave Camp rozbijasz namiot, wietrznym nocą do obserwacji nieba i doskonałe dla aklimatyzacji. Słońce zachodzi tu wolno, a poranki są krystalicznie czyste."),
            dict(title="Dzień 3: Second Cave 3450m → Kikelewa Camp 3 600 m",
                 stats=[("Dystans", "~6 km"), ("Przewyższenie", "+150 m"), ("Czas przejścia", "3–4 godziny"),
                        ("Temperatura", "10–15°C w dzień, 0–5°C w nocy"), ("Strefa", "strefa przejściowa – coraz bardziej surowa")],
                 desc="To krótki i łagodny dzień, który pozwala ciału złapać oddech i dostosować się do wysokości. Szlak wiedzie przez wypłaszczone tereny, na których z każdym kilometrem roślinność staje się rzadsza, a kolory bledną – zieleń ustępuje szarościom i brązom. Pojawiają się pierwsze oznaki pustynnego klimatu – wiatr, kurz, brak cienia. Po południu docierasz do Kikelewa – małego, klimatycznego obozu u stóp wzgórz. Nocą temperatura spada poniżej zera, a niebo jest pełne gwiazd. To miejsce ciszy, skupienia i regeneracji."),
            dict(title="Dzień 4: Kikelewa Camp 3600m → Mawenzi Tarn Camp 4 315 m",
                 stats=[("Dystans", "~4 km"), ("Przewyższenie", "+715 m"), ("Czas przejścia", "4–5 godzin"),
                        ("Temperatura", "5–10°C w dzień, -5 do 0°C w nocy"), ("Strefa", "alpejska pustynia")],
                 desc="Jeden z najbardziej malowniczych dni na trasie. Podejście pod Mawenzi jest krótkie, ale intensywne – pokonujesz ponad 700 metrów przewyższenia. Z każdym metrem w górę teren staje się coraz bardziej dramatyczny – ostre skały, czarna ziemia, echo Twoich kroków. Docierasz do Mawenzi Tarn – obozu położonego u stóp surowego, postrzępionego szczytu Mawenzi, nad małym górskim jeziorkiem. To jedno z najbardziej fotogenicznych miejsc na Kilimandżaro – cisza, przestrzeń, surowa natura i ogrom. To także ostatnia szansa, by dobrze się zaaklimatyzować przed podejściem na Kibo.",
                 note="W 6-dniowej wersji pomija się Mawenzi Tarn Camp – z Kikelewa od razu przejście do Kibo Hut."),
            dict(title="Dzień 5: Mawenzi Tarn 4315 m → Kibo Hut 4 720 m",
                 stats=[("Dystans", "~9 km"), ("Przewyższenie", "+405 m"), ("Czas przejścia", "5–6 godzin"),
                        ("Temperatura", "0–5°C w dzień, -5 do -10°C w nocy"), ("Strefa", "wysokogórska pustynia")],
                 desc="Ten etap to długa wędrówka przez tzw. Saddle – ogromne, księżycowe siodło rozciągające się pomiędzy Mawenzi i Kibo. Teren jest płaski, ale nieławy – szlak biegnie przez jałowe pustkowie, które wystawia psychikę i ciało na próbę. Słońce odbija się od pyłu, wiatr niesie zimno, a powietrze staje się coraz rzadsze. W oddali rośnie monumentalny Kibo – jak skalna forteca. Kibo Hut to minimalistyczny, skalny obóz bez roślinności, bez schronienia. Wszyscy myślą już tylko o jednym – o nocnym wyjściu na szczyt. To ostatni wieczór przed atakiem."),
            dict(title="Dzień 6: Kibo Hut 4720 m → Uhuru Peak 5 895 m → Horombo Hut (3 720 m)",
                 stats=[("Dystans", "~21 km (6 km do szczytu + 15 km zejścia)"), ("Przewyższenie", "+1 175 m / -2 175 m"),
                        ("Czas przejścia", "12–14 godzin"), ("Temperatura", "-10°C do -15°C w nocy, 0–5°C po świcie"),
                        ("Strefa", "lodowiec, strefa subarktyczna → wrzosowiska")],
                 desc="Startujesz w kompletnej ciemności, zazwyczaj około północy. Nocne podejście to rytmiczne, powolne stawianie kroków w ciszy – przez piach, skały i chłód. Zimno jest przenikliwe, a zmęczenie narasta. Najpierw osiągasz Gilman's Point, potem Stella Point, aż wreszcie – po kilku godzinach – stoisz na dachu Afryki, przy tabliczce Uhuru Peak. Słońce wschodzące nad chmurami maluje lodowiec w różowo-błękitne odcienie. Radość miesza się z wyczerpaniem. Zejście jest długie i wymagające – po południu docierasz do Horombo, gdzie czeka Cię ostatnia noc w górach i zasłużony sen."),
            dict(title="Dzień 7: Horombo Hut 3720 m → Marangu Gate 1 860 m",
                 stats=[("Dystans", "~20 km"), ("Przewyższenie", "-1 860 m"), ("Czas przejścia", "6–7 godzin"),
                        ("Temperatura", "15–20°C"), ("Strefa", "od wrzosowisk do lasu deszczowego")],
                 desc="To długa, końcowa wędrówka – przez znajome już wrzosowiska, a następnie gęsty, zielony las deszczowy. Z każdym krokiem robi się coraz cieplej i wilgotniej, wracają dźwięki ptaków, zapachy ziemi i dżungli. Kolana dają znać o sobie, ale w sercu lekkość – zrobiłeś to. Przy Marangu Gate podpisujesz się na liście, odbierasz certyfikat, ściskasz rękę przewodnika. To koniec trekkingu, ale początek opowieści, która zostaje na zawsze."),
        ],
        table=dict(
            cols=["Wersja", "Aklimatyzacja", "Czas na regenerację", "Skuteczność wejścia"],
            rows=[
                ["7 dni", "mniejsza – brak noclegu w Shira 1", "mniej odpoczynku, intensywniejsze wejście", "umiarkowana (~80–85%)"],
                ["8 dni", "lepsza – stopniowy wzrost wysokości (Shira 1 + Shira 2)", "więcej czasu na adaptację i sen", "bardzo wysoka (~90–95%)"],
            ],
            title="Różnice między wersją 7- a 8-dniową:",
        ),
    ),

    # ------------------------------------------------------------------ #
    "Shira": dict(
        title="Shira",
        meta="Długość 56 km  |  Czas 6–7 dni  |  Trudność umiarkowana fizycznie, ale trudna aklimatyzacyjnie (startuje bardzo wysoko!)  |  Przewyższenie: 2481 m",
        good_if_title="To może być Twoja droga, jeśli:",
        good_if=[
            "szukasz mniej uczęszczanej, dzikiej drogi z szybkim wejściem w strefę wysokogórską,",
            "masz już doświadczenie w trekkingu na większych wysokościach i wiesz, jak reaguje Twój organizm – błyskawiczna aklimatyzacja.",
            "cenisz spektakularne panoramy od pierwszego dnia – płaskowyż Shira zachwyca rozległymi widokami na dolinę i wulkan Kibo,",
            "chcesz uniknąć tłumów – ta trasa jest znacznie mniej popularna niż Machame czy Marangu,",
            "Jesteś gotów wystartować wysoko (brama na 3 414 m).",
            "chcesz połączyć malowniczość trasy Lemosho z krótszym czasem przejścia – Shira to mniej znana, ale wciąż wymagająca alternatywa,",
            "pociąga Cię przestrzeń i surowość górskiej pustyni – dni trekkingowe prowadzą przez księżycowy krajobraz wyżyny Shira i alpejskiej pustyni.",
        ],
        days=[
            dict(title="Dzień 1: Shira Gate (3 414 m) → Shira 1 Camp (3 610 m)",
                 stats=[("Dystans", "~5 km"), ("Przewyższenie", "+196 m (niewielkie, ale już na dużej wysokości)"), ("Czas przejścia", "1,5–2 godziny"),
                        ("Temperatura", "10–15°C w dzień, 0–5°C w nocy"), ("Strefa klimatyczna", "wrzosowiska / zarośla wysokogórskie")],
                 desc="Trekking zaczynasz nietypowo – nie od bujnego lasu tropikalnego, jak na wielu innych trasach, lecz od razu na otwartej przestrzeni płaskowyżu Shira. Już pierwszego dnia znajdujesz się powyżej 3 600 m n.p.m., co oznacza zarówno spektakularne widoki, jak i wyraźne ryzyko choroby wysokościowej. Teren jest odsłonięty i porośnięty niską trawą oraz zaroślami lobelii, a powietrze ma już inną gęstość – wędrówka może wydawać się łatwa technicznie, ale trudna oddechowo. Lekki ból głowy, senność lub spowolnienie tempa to zupełnie normalna reakcja. Shira 1 Camp leży w chłodnym i wietrznym miejscu, z piękną panoramą na zachodnie doliny i pierwszym spojrzeniem na wulkan Kibo.",
                 note="Wersja 6-dniowa pomija ten dzień z noclegiem w Shira 1 Camp – trekking idzie do Shira 2 (3 850 m), co oznacza bardzo szybkie wejście na dużą wysokość i duże ryzyko choroby wysokościowej."),
            dict(title="Dzień 2: Shira 1 3610 m → Shira 2 Camp (3 850 m)",
                 stats=[("Dystans", "~7 km"), ("Przewyższenie", "+240 m"), ("Czas przejścia", "3–4 godziny"),
                        ("Temperatura", "8–12°C w dzień, 0–3°C w nocy"), ("Strefa", "alpejska pustynia")],
                 desc="Poranek na płaskowyżu Shira wita Cię ciszą i chłodem, z bezkresnym horyzontem, który zdaje się nie mieć końca. Tego dnia kontynuujesz trekking przez księżycowy krajobraz – niemal całkowicie pozbawiony drzew, z twardą, czarną ziemią i niskimi roślinami. W oddali dominuje sylwetka Kibo, pokryta lodowcem, a na horyzoncie czasem majaczy Mawenzi – drugi z wulkanicznych szczytów Kilimandżaro. Dzień jest krótki, ale wysokość daje się we znaki – każdy krok jest wolniejszy, a ciało stara się dostosować do nowej rzeczywistości. To dobry moment, by obserwować reakcje organizmu i dużo pić. Shira 2 Camp to wietrzne, otwarte miejsce – noc tutaj potrafi być bardzo zimna."),
            dict(title="Dzień 3: Shira 2 3850m → Lava Tower 4 600 m → Barranco Camp 3 900 m",
                 stats=[("Dystans", "~10 km"), ("Przewyższenie", "+750 m / -700 m"), ("Czas przejścia", "6–7 godzin"),
                        ("Temperatura", "5–10°C w dzień, -2°C w nocy"), ("Strefa", "alpejska pustynia / strefa subarktyczna")],
                 desc="To jeden z najważniejszych dni aklimatyzacyjnych na całej trasie. Podejście pod Lava Tower, skalną iglicę wznoszącą się na 4 600 m n.p.m., to solidne wyzwanie – dla nóg, płuc i głowy. Powietrze staje się wyraźnie rzadsze, a każdy krok wymaga większego wysiłku. Objawy wysokościowe mogą się nasilić: zawroty głowy, zadyszka, osłabienie – dlatego tempo jest wolne, a postój przy Lava Tower strategiczny. Następnie schodzisz kilkaset metrów w dół do Barranco – przepięknego obozu położonego w dolinie, otoczonego olbrzymimi senecjami i stromymi ścianami. To „walk high, sleep low” w praktyce – kluczowe dla Twojej adaptacji. Zachód słońca nad Kibo z tej perspektywy zapiera dech w piersiach."),
            dict(title="Dzień 4: Barranco Camp 3900m → Karanga Camp 3 995 m",
                 stats=[("Dystans", "~6 km"), ("Przewyższenie", "+95 m netto (duże podejście na początku)"), ("Czas przejścia", "4–5 godzin"),
                        ("Temperatura", "5–10°C w dzień, -3°C w nocy"), ("Strefa", "ściana Barranco i doliny")],
                 desc="Dzień zaczynasz od pokonania słynnej Ściany Barranco – imponującej, kilkusetmetrowej formacji skalnej. Choć wygląda przerażająco, nie wymaga specjalistycznych umiejętności – to raczej ekscytujące podejście „na cztery kończyny”, które daje niesamowite widoki i dużo satysfakcji. Po osiągnięciu grani szlak schodzi w doliny i ponownie wznosi się na niewielkich przełęczach. To dzień pełen naturalnych rytmów – podejście, zejście, oddech, krok. Choć przewyższenie netto jest niewielkie, całościowy wysiłek daje się we znaki. Karanga Camp to miejsce osłonięte, z surowym, skalistym otoczeniem. To ostatnia noc przed wejściem w najwyższe partie góry."),
            dict(title="Dzień 5: Karanga 3995 m → Barafu Camp 4 673 m",
                 stats=[("Dystans", "~4 km"), ("Przewyższenie", "+678 m"), ("Czas przejścia", "3–4 godziny"),
                        ("Temperatura", "0–5°C w dzień, -5 do -10°C w nocy"), ("Strefa", "pustynia alpejska")],
                 desc="Krótki, ale wymagający etap przez surowe, skaliste pustkowie. Szlak prowadzi przez rumowiska wulkaniczne i sypkie piargi – przy każdym kroku ziemia może się osuwać pod stopami. Otoczenie jest niemal całkowicie pozbawione życia – to strefa pustyni alpejskiej, gdzie przetrwają tylko najbardziej odporne organizmy. Obóz Barafu leży na wysoko położonym grzbiecie, często pod śniegiem, z panoramicznym widokiem na wschód. Tu już nikt nie myśli o zdjęciach – wieczór służy pakowaniu plecaka, przygotowywaniu warstw odzieży i mentalnemu nastawieniu na nocny atak szczytowy. Sen, jeśli w ogóle przychodzi, jest lekki i niespokojny."),
            dict(title="Dzień 6: Barafu 4673 m → Uhuru Peak 5 895 m → Mweka Camp 3100 m",
                 stats=[("Dystans", "5 km podejścia, 12 km zejścia"), ("Przewyższenie", "+1 222 m / -2 795 m"),
                        ("Czas przejścia", "12–14 godzin"), ("Temperatura", "-10°C do -15°C w nocy, 0–5°C po wschodzie"),
                        ("Strefa", "lodowiec, strefa subarktyczna → wrzosowiska")],
                 desc="Atak szczytowy rozpoczyna się tuż po północy. Wyruszasz w całkowitej ciemności, w ciszy przerywanej tylko oddechami i skrzypieniem butów po żwirze. Każdy krok na stromym zboczu wymaga skupienia i silnej woli. Im bliżej grani, tym zimniej – temperatura może spaść poniżej -15°C. Stella Point wita Cię o świcie – a od niego jeszcze godzina marszu do Uhuru Peak, najwyższego punktu Afryki. Gdy stoisz na szczycie, wszystko cichnie – tylko lodowce, przestrzeń i wzruszenie. Zejście z powrotem do Barafu to pierwszy etap ulgi, ale prawdziwe zmęczenie przychodzi dopiero później – zejście aż do Mweka Camp to kilkaset metrów w pionie po sypkim gruncie. To najdłuższy, najbardziej wyczerpujący dzień wyprawy – ale też najpiękniejszy."),
            dict(title="Dzień 7: Mweka Camp 3100 m → Mweka Gate 1 640 m",
                 stats=[("Dystans", "~10 km"), ("Przewyższenie", "-1 460 m"), ("Czas przejścia", "3–4 godziny"),
                        ("Strefa", "wilgotny las"), ("Temperatura", "20–25°C")],
                 desc="Ostatni odcinek wiedzie przez gęsty, pachnący las deszczowy. Szlak bywa błotnisty i śliski, ale ciało odpuszcza – jesteś po wszystkim. Śpiew ptaków, świeże powietrze i dźwięk liści pod stopami tworzą niemal medytacyjną atmosferę. Gdy docierasz do bramy parku, czeka na Ciebie certyfikat, gratulacje, śmiechy z przewodnikami. Ale też coś więcej – poczucie, że zrobiłeś coś naprawdę wyjątkowego."),
        ],
        table=TABLE_78,
        table_note="Na stronie tabela podpisana 7/8 dni — sprawdź, czy dla Shiry nie powinna być 6/7.",
    ),

    # ------------------------------------------------------------------ #
    "Umbwe": dict(
        title="Umbwe",
        meta="Długość 53 km  |  Czas 5–6 dni  |  Trudność bardzo wysoka – najkrótsza i najbardziej stroma klasyczna trasa na Kilimandżaro  |  Przewyższenie: 4095 m",
        good_if_title="Wybierz tę drogę, jeśli:",
        good_if=[
            "Szukasz najbardziej stromej i wymagającej trasy na Kilimandżaro",
            "Masz bardzo dobrą kondycję i doświadczenie w górach wysokich",
            "Lubisz iść na lekko i szybko, bez tłumów i zbędnych przerw",
            "Nie boisz się ekspozycji, stromych zboczy i surowego terenu",
            "Chcesz poczuć dzikość góry bez filtra – tu nie ma łagodnych początków",
            "Znasz swój organizm i wiesz, jak reaguje na wysokość",
            "Wolisz krótszy trekking, nawet kosztem aklimatyzacji i komfortu",
        ],
        days=[
            dict(title="Dzień 1: Umbwe Gate 1 800 m → Umbwe Cave Camp 2 850 m",
                 stats=[("Dystans", "~9 km"), ("Przewyższenie", "+1050 m"), ("Czas przejścia", "5–7 godzin"),
                        ("Temperatura", "18–22°C w dzień, 8–10°C w nocy"), ("Strefa klimatyczna", "las deszczowy")],
                 desc="Już od pierwszego kroku Umbwe nie daje złudzeń – to trasa dla zdecydowanych. Szlak zaczyna się niemal od razu stromym podejściem przez gęsty, parujący las deszczowy. Wysoka wilgotność sprawia, że koszulka szybko robi się mokra, a każda przerwa w marszu przynosi błyskawiczne ochłodzenie. Zakosy prowadzą ostro pod górę, przez plątaninę korzeni i omszałych drzew. Nie ma tu miejsca na łagodne wejście – to brutalne zanurzenie w dzikość góry. W miarę zdobywania wysokości las zaczyna się przerzedzać, pojawia się więcej światła i coraz częściej czujesz rześki, górski wiatr. Obóz położony jest jeszcze w strefie leśnej, ale czuć już surowość wysokości. Noc pod baldachimem mgły i liści to pierwsze poważne spotkanie z Kilimandżaro."),
            dict(title="Dzień 2: Umbwe Cave Camp 2850 → Barranco Camp (3 900 m)",
                 stats=[("Dystans", "~6 km"), ("Przewyższenie", "+1 050 m"), ("Czas przejścia", "4–5 godzin"),
                        ("Temperatura", "10–15°C w dzień, 0–5°C w nocy"), ("Strefa", "wrzosowiska / alpejskie zarośla")],
                 desc="Od rana ruszasz dalej w górę – ostro, bez litości, przez coraz bardziej odsłonięty teren. Las znika szybko, ustępując miejsca wysokogórskim zaroślom i wrzosowiskom. Szlak wspina się grzbietem, czasem prowadząc wąską ścieżką tuż przy stromym zboczu. Ekspozycja i nagła zmiana krajobrazu robią ogromne wrażenie – widok na Barranco Wall w oddali zapowiada, co czeka Cię kolejnego dnia. Choć dystans nie jest duży, przewyższenie i ekspozycja sprawiają, że marsz jest wymagający. Gdy docierasz do Barranco Camp, witasz się z zupełnie innym światem: dolina z gigantycznymi senecjami, czarne ściany skalne i surowa cisza. To jedno z najpiękniejszych i najbardziej surowych miejsc na całym Kilimandżaro."),
            dict(title="Dzień 3: Barranco Camp 3900 → Karanga Camp 3 995 m",
                 stats=[("Dystans", "~6 km"), ("Przewyższenie", "+95 m (duże podejścia i zejścia po drodze)"), ("Czas przejścia", "4–5 godzin"),
                        ("Temperatura", "5–10°C w dzień, -3°C w nocy"), ("Strefa", "skaliste przełęcze i doliny")],
                 desc="Pierwsze wyzwanie dnia to słynna Barranco Wall – imponująca, pionowa formacja skalna, która budzi respekt, ale nie wymaga technicznego wspinania. Wąskie przejścia i odcinki „na cztery kończyny” dają adrenalinę i poczucie bliskości z górą. Po zdobyciu grani szlak łagodnie faluje, prowadząc przez skaliste doliny i niewielkie przełęcze. Choć suma przewyższeń netto jest niewielka, ciągłe podejścia i zejścia potrafią zmęczyć psychicznie. To dzień balansowania – między zmęczeniem a mobilizacją, między kamieniami a cieniem. Karanga Camp, choć niepozorny, oferuje noc w pełni górskiej ciszy i chłodu – temperatura często spada poniżej zera, a niebo rozświetlają miliony gwiazd.",
                 note="Wersja 5-dniowa łączy dni 3 i 4 (czyli Barranco → Barafu), co oznacza bardzo długi i intensywny dzień tuż przed atakiem szczytowym."),
            dict(title="Dzień 4: Karanga Camp 3995m → Barafu Camp 4 673 m",
                 stats=[("Dystans", "~4 km"), ("Przewyższenie", "+678 m"), ("Czas przejścia", "3–4 godziny"),
                        ("Temperatura", "0–5°C w dzień, -10°C w nocy"), ("Strefa", "pustynia wysokogórska")],
                 desc="Ten etap to marsz przez pustynię – kamienistą, suchą, bez cienia. Szlak wspina się stabilnie, ale konsekwentnie, prowadząc przez martwy, jałowy krajobraz. Brak roślinności, brak punktów odniesienia – tylko Ty, plecak i daleki cel. Słońce pali, wiatr chłodzi, a każdy krok to walka z grawitacją i zmęczeniem. Barafu Camp leży wysoko, na skalnej półce, z widokiem na lodowce Kibo i wschodnią krawędź krateru. Panuje tu atmosfera skupienia – to miejsce nie na odpoczynek, lecz na mobilizację. Wszyscy są cicho, przygotowują sprzęt, ubierają warstwy, rozkładają czołówki. To ostatni przystanek przed wielką nocą."),
            dict(title="Dzień 5: Barafu Camp 4673 m → Uhuru Peak 5 895 m → Mweka Camp 3 100 m",
                 stats=[("Dystans", "~17 km (5 km podejścia, 12 km zejścia)"), ("Przewyższenie", "+1 222 m / -2 795 m"),
                        ("Czas przejścia", "12–14 godzin"), ("Temperatura", "-10°C do -15°C w nocy, 0–5°C po wschodzie"),
                        ("Strefa", "śnieg, lód, żwir → wrzosowiska")],
                 desc="Wyruszasz w nocy – w ciemności, w ciszy, w skupieniu. Szlak wspina się ostro po sypkich piargach, wśród skał i lodu. Oddech robi się płytki, a kroki coraz wolniejsze. To moment, w którym siła psychiczna staje się ważniejsza niż kondycja – tylko rytm: krok – oddech – krok. Gdy wreszcie pojawia się Stella Point, a potem Uhuru – słońce zaczyna wschodzić nad chmurami, oświetlając lodowce i szczytową krawędź krateru. Na dachu Afryki panuje cisza – nie z braku słów, a z pełni emocji. Zejście to kolejny test – tym razem dla kolan, stóp i koncentracji. Po drodze mijasz znane już punkty, a świat powoli wraca do życia. Mweka Camp wita Cię jak schronienie – zmęczony, wyczerpany, ale szczęśliwy, wracasz na niższą wysokość."),
            dict(title="Dzień 6: Mweka Camp 3100 m → Mweka Gate 1 640 m",
                 stats=[("Dystans", "~10 km"), ("Przewyższenie", "-1 460 m"), ("Czas przejścia", "3–4 godziny"),
                        ("Temperatura", "15–25°C"), ("Strefa", "las deszczowy")],
                 desc="Powrót przez las deszczowy to jak przejście między dwoma światami. Wczoraj – lód, skały i najwyższy szczyt Afryki. Dziś – zieleń, zapach ziemi, śpiew ptaków. Szlak bywa śliski, błotnisty i nieco zdradliwy, ale już bez pośpiechu – krok po kroku wracasz do świata ludzi. Na dole, przy bramie parku, podpisujesz się w książce wejść, odbierasz certyfikat, ściskasz rękę przewodnika. Umbwe była surowa, dzika, wymagająca. I właśnie dlatego – nie do zapomnienia."),
        ],
        table=dict(
            cols=["Wersja", "Aklimatyzacja", "Czas na regenerację", "Skuteczność wejścia"],
            rows=[
                ["7 dni", "mniejsza – brak noclegu w Shira 1", "mniej odpoczynku, intensywniejsze wejście", "umiarkowana (~80–85%)"],
                ["8 dni", "lepsza – stopniowy wzrost wysokości (Shira 1 + Shira 2)", "więcej czasu na adaptację i sen", "bardzo wysoka (~90–95%)"],
            ],
            title="Różnice między wersją 7- a 8-dniową:",
        ),
    ),

    # ------------------------------------------------------------------ #
    "Northern Circuit": dict(
        title="Northern Circuit",
        meta="Długość 88–96 km  |  Czas 8–10 dni  |  Trudność umiarkowana fizycznie, świetna aklimatyzacyjnie  |  Przewyższenie: 3795 m",
        good_if_title="Wybierz tę drogę, jeśli:",
        good_if=[
            "Chcesz mieć najwięcej czasu na aklimatyzację i adaptację do wysokości",
            "Zależy Ci na najwyższym wskaźniku wejścia na szczyt (nawet 95%)",
            "Szukasz spokoju, samotności i mniej uczęszczanej trasy",
            "Chcesz zobaczyć północną, dzikszą stronę Kilimandżaro, niedostępną z innych szlaków",
            "Lubisz, gdy trekking to proces, a nie wyścig",
            "Masz dobrą kondycję i jesteś gotów poświęcić 8–10 dni w górach",
            "Szukasz pełnego doświadczenia – z widokami, czasem dla siebie i prawdziwym wyciszeniem",
        ],
        days=[
            dict(title="Dzień 1: Lemosho Gate 2 100 m → Mti Mkubwa Camp 2 650 m",
                 stats=[("Dystans", "~6 km"), ("Przewyższenie", "+550 m"), ("Czas przejścia", "3–4 godziny"),
                        ("Temperatura", "15–20°C w dzień, 8–10°C w nocy"), ("Strefa klimatyczna", "las deszczowy")],
                 desc="Startujesz z dala od tłumów, w dzikiej części zachodnich zboczy Kilimandżaro. Już na początku czeka Cię wejście w gęsty las deszczowy – pełen mchu, pajęczyn i wilgotnych korzeni. Szlak jest wąski, miejscami stromy, otoczony przez paprocie i chaszcze, a powietrze ciężkie od wilgoci. Często pod nogami leży błoto, dlatego kijki i wodoodporne buty to podstawa. Co jakiś czas zatrzymujesz się – nie tylko na oddech, ale i na obserwację: z drzew mogą wyglądać małpy colobus, a nad głową przelatują barwne ptaki. Obóz Mti Mkubwa to kameralne miejsce położone tuż przy granicy lasu i wrzosowisk – z ciszą, chłodniejszym powietrzem i pierwszym uczuciem „jestem w górach”."),
            dict(title="Dzień 2: Mti Mkubwa 2650m → Shira 1 Camp 3 610 m",
                 stats=[("Dystans", "~8 km"), ("Przewyższenie", "+960 m"), ("Czas przejścia", "5–6 godzin"),
                        ("Temperatura", "10–15°C w dzień, 0–5°C w nocy"), ("Strefa klimatyczna", "wrzosowiska i zarośla")],
                 desc="Rano żegnasz las, a niemal od razu pojawiają się pierwsze otwarte widoki. Wspinaczka prowadzi przez porośnięte krzewami stoki, skąd rozpościerają się panoramy zachodniej części Kilimandżaro. Teren staje się bardziej kamienisty, a roślinność rzadsza – dominują lobelie i senecje, rosnące jak bajkowe totemy. Kibo – główny wierzchołek – pojawia się pierwszy raz na horyzoncie, pokryty lodem i wydający się wciąż bardzo odległy. Szlak przechodzi przez kilka tarasów wulkanicznych, a im bliżej Shira 1, tym silniejszy może być wiatr. Obóz leży na otwartej przestrzeni płaskowyżu – rozciągnięty, z niskimi roślinami, wspaniałymi zachodami słońca i zimnymi nocami. Czuć, że to już wysokie góry.",
                 note="Wersja 7-dniowa pomija ten dzień z noclegiem w Shira 1 Camp – w tym dniu idzie się dłużej aż do Shira 2, co oznacza większe przewyższenie i mniej czasu na adaptację."),
            dict(title="Dzień 3: Shira 1 Camp 3610 m → Shira 2 Camp (3 850 m)",
                 stats=[("Dystans", "~7 km"), ("Przewyższenie", "+240 m"), ("Czas przejścia", "3–4 godziny"),
                        ("Temperatura", "8–12°C w dzień, 0–3°C w nocy"), ("Strefa", "alpejska pustynia")],
                 desc="Poranek na płaskowyżu Shira wita Cię ciszą i chłodem, z bezkresnym horyzontem, który zdaje się nie mieć końca. Tego dnia kontynuujesz trekking przez księżycowy krajobraz – niemal całkowicie pozbawiony drzew, z twardą, czarną ziemią i niskimi roślinami. W oddali dominuje sylwetka Kibo, pokryta lodowcem, a na horyzoncie czasem majaczy Mawenzi – drugi z wulkanicznych szczytów Kilimandżaro. Dzień jest krótki, ale wysokość daje się we znaki – każdy krok jest wolniejszy, a ciało stara się dostosować do nowej rzeczywistości. To dobry moment, by obserwować reakcje organizmu i dużo pić. Shira 2 Camp to wietrzne, otwarte miejsce – noc tutaj potrafi być bardzo zimna."),
            dict(title="Dzień 4: Shira 2 Camp 3850 m → Lava Tower 4 600 m → Moir Hut 4 161 m",
                 stats=[("Dystans", "~10 km"), ("Przewyższenie", "+750 m / -439 m"), ("Czas przejścia", "6–7 godzin"),
                        ("Temperatura", "5–10°C w dzień, -2°C w nocy"), ("Strefa", "pustynia alpejska")],
                 desc="Dzień typu „walk high, sleep low” – klasyczna i niezwykle skuteczna aklimatyzacja. Podejście pod Lava Tower to pierwszy kontakt z wysokością powyżej 4500 – wiele osób odczuwa tu ból głowy, senność, spadek energii. Ale to właśnie o to chodzi – by organizm dostał impuls do adaptacji. Po krótkim postoju zaczynasz zejście do ukrytej doliny Moir – jednego z najbardziej odludnych obozów na całym Kilimandżaro. Nikt tu nie dociera „przypadkiem”. Jest cicho, spokojnie, a wieczorne światło rozlewa się po ciemnoszarych skałach niczym filmowa scena. Dla wielu – najpiękniejsze miejsce całej trasy.",
                 note="W wersji 8 dniowej trekkingu pomijany jest nocleg w Moir Hut – trekking jest od razu do Buffalo Camp na 4023 m."),
            dict(title="Dzień 5: Moir Hut 4161 m → Buffalo Camp 4 023 m",
                 stats=[("Dystans", "~9 km"), ("Przewyższenie", "-138 m"), ("Czas przejścia", "5–6 godzin"),
                        ("Temperatura", "5–10°C w dzień, -3°C w nocy"), ("Strefa", "północne zbocza góry, otwarte")],
                 desc="W tym dniu zaczynasz obchodzenie masywu Kibo od północnej, dzikiej strony. To najrzadziej uczęszczany fragment Kilimandżaro – nie spotkasz tu tłumów, a może nawet nikogo. Szlak prowadzi przez otwarte przestrzenie, półki skalne i łagodne grzbiety. Cisza jest gęsta, a wiatr niesie pustkę. Marsz nie jest trudny technicznie, ale działa na wyobraźnię – jesteś sam na sam z górą. Buffalo Camp to surowe miejsce na skraju strefy roślinności – czeka Cię chłodna, ale spokojna noc, daleko od cywilizacji.",
                 note="W wersji 10 dniowej trekkingu dodaje się dzień aklimatyzacyjny w Buffalo Camp lub ewentualnie dzień szybciej Moir Hut."),
            dict(title="Dzień 6: Buffalo Camp 4023 m → Third Cave Camp 3 800 m",
                 stats=[("Dystans", "~8 km"), ("Przewyższenie", "-223 m"), ("Czas przejścia", "4–5 godzin"),
                        ("Temperatura", "6–10°C w dzień, -1°C do -3°C w nocy"), ("Strefa", "alpejska pustynia")],
                 desc="Dzień regeneracyjny – łagodna, płynna wędrówka przez północną część masywu. Szlak faluje spokojnie, pozwalając ciału odpocząć i wyrównać poziomy energii. Roślinność już niemal całkiem zniknęła, zostały tylko piargi, kamienie i niebo. Third Cave Camp to kolejne odludne miejsce – samotność, wiatr, bliskość surowej natury. Wieczorem cisza jest tak głęboka, że słychać własne myśli. To dzień, który przygotowuje nie tylko ciało, ale i głowę na najważniejsze podejście całej wyprawy."),
            dict(title="Dzień 7: Third Cave Camp 3800 m → School Hut 4 710 m",
                 stats=[("Dystans", "~5 km"), ("Przewyższenie", "+910 m"), ("Czas przejścia", "4–5 godzin"),
                        ("Temperatura", "3–7°C w dzień, -5°C w nocy"), ("Strefa", "skaliste zbocza i pustynia")],
                 desc="To ostatni odcinek przed szczytem. Podejście na School Hut jest konkretne – ponad 900 metrów w górę, przez skaliste rumowiska i wietrzne przełęcze. Marsz wymaga skupienia, ale motywuje fakt, że to już ostatni dzień wędrówki przed atakiem na Uhuru. School Hut to surowy, funkcjonalny obóz – bez widoków, bez rozpraszaczy. Wszyscy są tu po to, by odpocząć kilka godzin, zjeść lekką kolację, przygotować warstwy ubrań i czołówki. Noc nie przynosi snu – tylko czekanie."),
            dict(title="Dzień 8: School Hut 4710 m → Uhuru Peak 5 895 m → Mweka Camp 3 100 m",
                 stats=[("Dystans", "~16 km"), ("Przewyższenie", "+1 145 m / -2 795 m"), ("Czas przejścia", "12–14 godzin"),
                        ("Temperatura", "-10°C do -15°C w nocy, 0–5°C po wschodzie, 10–15°C w Mweka Camp po południu"),
                        ("Strefa", "lodowiec → wrzosowiska")],
                 desc="Wyjście w ciemność. Podejście strome, techniczne, sypkie – krok za krokiem, w rytmie oddechu. Wschód słońca zastaje Cię na grani – Stella Point lub Gilman's Point, zależnie od tempa. Ostatni fragment na Uhuru Peak to emocje, wyczerpanie, niedowierzanie. I nagle – jesteś na szczycie. Najwyższy punkt Afryki, pokryty lodem, oświetlony porannym słońcem. Nie da się tego porównać z niczym. Potem długie zejście – najpierw do Barafu, później do Mweka. Kolana krzyczą, stopy pieką, ale głowa już odpoczywa. W obozie wieczorem – śmiech, łzy i ulga."),
            dict(title="Dzień 9: Mweka Camp 3100 m → Mweka Gate (1 640 m)",
                 stats=[("Dystans", "~10 km"), ("Przewyższenie", "-1 460 m"), ("Czas przejścia", "3–4 godziny"),
                        ("Temperatura", "18–25°C w dzień, 12–15°C w nocy"), ("Strefa", "las deszczowy")],
                 desc="Powrót do zieleni. Las deszczowy wita Cię znów – tym razem jako zwycięzcę. Szlak mokry, śliski, ale już bez presji. Po drodze ptaki, zapach liści i błota, śmiechy z przewodnikiem, opowieści o tym, co wydarzyło się przez ostatnie dni. Przy bramie parku – certyfikat, gratulacje i uczucie, którego nie da się łatwo opisać. Northern Circuit to nie tylko droga na szczyt – to transformacja. Zrobiłeś to powoli, mądrze i w zgodzie z rytmem góry."),
        ],
        table=TABLE_78,
        table_note="Na stronie tabela podpisana 7/8 dni — Northern Circuit ma 8–10 dni, więc warto zweryfikować jej treść.",
    ),

    # ------------------------------------------------------------------ #
    "Western Breach": dict(
        title="Western Breach Route – 7 dni",
        meta="Długość ok 72 km*  |  Czas 6–7 dni  |  Trudność bardzo wysoka – wymagająca kondycyjnie i technicznie.  |  Przewyższenie: ok 4000 m (w zależności od trasy dojściowej, np. Machame, Lemosho, Umbwe)",
        good_if_title="Sprawdzi się, jeśli:",
        good_if=[
            "Masz bardzo dobrą kondycję i doświadczenie górskie",
            "Szukasz krótszej, intensywniejszej drogi na szczyt",
            "Chcesz wejść mniej uczęszczaną, surową i technicznie trudniejszą trasą",
            "Nie boisz się stromych, skalnych podejść i ekspozycji",
            "Marzysz o wejściu przez lodowcową ścianę Kibo – najbardziej bezpośrednią drogą",
            "Nie szukasz komfortu – ale surowej przygody i emocji",
            "Jesteś świadomy ryzyka: spadające kamienie, brak możliwości szybkiej ewakuacji, potrzebne specjalne pozwolenie",
        ],
        days=[
            dict(title="Dzień 3: Shira 1 Camp 3610 m → Lava Tower 4 600 m",
                 stats=[("Dystans", "~9 km"), ("Przewyższenie", "+ 990 m"), ("Czas", "6–7 godzin"),
                        ("Strefa", "alpejska pustynia"), ("Temperatura", "5–10°C w dzień, -3°C do -5°C w nocy")],
                 desc="To dzień intensywnej aklimatyzacji i pierwszej konfrontacji z poważną wysokością. Szlak prowadzi przez jałowy, pylisty krajobraz – bez drzew, bez cienia, z niebem jak wypłowiała płandeka nad głową. Marsz jest długi i męczący – tlen ucieka z płuc szybciej, niż się spodziewasz. Lava Tower wyrasta nagle – czarna, poszarpana kolumna skalna, jak strażnik broniący wejścia w wyższe partie Kibo. Tu nie ma już miejsca na niedbałość – organizm pokazuje, czy jest gotowy. Wieczorem nocleg pod skałami, w cieniu tego, co jutro stanie przed Tobą naprawdę."),
            dict(title="Dzień 4: Lava Tower 4600 m → Arrow Glacier Camp 4 903 m",
                 stats=[("Dystans", "~2 km (krótko, ale stromo)"), ("Przewyższenie", "+303 m"), ("Czas", "2–3 godziny"),
                        ("Strefa", "strefa wysokogórska, śnieg i lód"), ("Temperatura", "0–5°C w dzień, -5°C do -10°C w nocy")],
                 desc="To krótki dystans, ale intensywny dzień. Podejście strome, szlak biegnie przez sypkie piargi i kamienne uskoki. Z każdą godziną stajesz twarzą w twarz z Western Breach – potężną, surową ścianą skalną pokrytą żebrami lawy i jęzorami lodu. Arrow Glacier Camp leży u jej stóp – to miejsce niepokojąco piękne i puste. Cisza jest absolutna, a każdy odgłos niesie się echem. Tu już nic nie jest komfortowe – kamienie pod śpiworem, przenikliwy wiatr, świadomość, że z tego miejsca nie ma łatwego odwrotu. To ostatnia noc przed największym wyzwaniem."),
            dict(title="Dzień 5: Arrow Glacier 4903 m → Uhuru Peak 5 895 m → Crater Camp 5 750 m",
                 stats=[("Dystans", "~4–5 km"), ("Przewyższenie", "+992 m / -145 m"), ("Czas", "6–8 godzin"),
                        ("Strefa", "śnieg, lód, krater"), ("Temperatura", "-10°C do -15°C")],
                 desc="Najbardziej ekstremalny dzień całej trasy. Wyruszasz o świcie – bez tłumów, bez czołówek na szlaku – bo nikt inny tędy nie idzie. Podejście przez Western Breach to nie spacer – to wspinaczka przez skalne półki, kruszące się żleby, śnieg i lód. Wymaga siły, zimnej krwi i ciągłej uwagi. To jedyna droga, która prowadzi bezpośrednio na krawędź krateru – żadnych zakosów, tylko prosto w ścianę. Gdy stajesz na górze, widok krateru z bliska powala – śnieg, popiół, lodowe seraki. Krótki marsz po lodzie i jesteś na Uhuru – szczyt jest tuż obok. Zamiast schodzić od razu, zostajesz na noc w Crater Camp, jednym z najwyżej położonych miejsc noclegowych na Ziemi. To noc dla odważnych – zimna, surowa, ale jak z innego świata.",
                 note="W wersji 6-dniowej zejście odbywa się od razu do Mweka Camp (brak noclegu w Crater Camp)."),
            dict(title="Dzień 6: Crater Camp 5740 m → Mweka Camp 3 100 m",
                 stats=[("Dystans", "~12–14 km"), ("Przewyższenie", "-2 630 m"), ("Czas", "6–7 godzin"),
                        ("Strefa", "wrzosowiska → las tropikalny"), ("Temperatura", "10–20°C w dolinie")],
                 desc="Rano wita Cię słońce odbijające się od lodowców – obraz, którego nie zapomnisz do końca życia. Zejście zaczyna się gwałtownie – z wysokości niemal 6 000 metrów schodzisz przez skalne pustkowia aż do strefy wrzosowisk. To długa, techniczna droga – kolana cierpią, stopy bolą, ale z każdym krokiem wracasz do świata pełnego tlenu, zapachów i dźwięków. Mweka Camp, położony w zielonej strefie przejściowej, wydaje się jak raj – namiot stoi na miękkiej ziemi, a w powietrzu czuć wilgoć i życie. To ostatnia noc na górze – noc pełna ulgi."),
            dict(title="Dzień 7: Mweka Camp 3100 m → Mweka Gate 1 640 m",
                 stats=[("Dystans", "~10 km"), ("Przewyższenie", "-1 460 m"), ("Czas", "3–4 godziny"),
                        ("Strefa", "wilgotny las"), ("Temperatura", "20–25°C")],
                 desc="Ostatni odcinek wiedzie przez gęsty, pachnący las deszczowy. Szlak bywa błotnisty i śliski, ale ciało odpuszcza – jesteś po wszystkim. Śpiew ptaków, świeże powietrze i dźwięk liści pod stopami tworzą niemal medytacyjną atmosferę. Gdy docierasz do bramy parku, czeka na Ciebie certyfikat, gratulacje, śmiechy z przewodnikami. Ale też coś więcej – poczucie, że zrobiłeś coś naprawdę wyjątkowego. Western Breach to trasa nie dla każdego. Nie oferuje wygody, ale daje coś znacznie cenniejszego: przeżycie, które zostaje w Tobie na zawsze."),
        ],
        table=TABLE_78,
        table_note="Dni 1–2 (dojście, np. Lemosho/Machame/Umbwe) i tabela wersji — do potwierdzenia ze strony.",
        partial_note="Uwaga: trasa pokazuje dni 3–7 (część dojściowa zależy od wybranego wariantu). Dni 1–2 do uzupełnienia, jeśli były osobno na stronie.",
    ),

}
